# #todo
#
##Todo List
#
#The version of the OpenAPI document: 1.0.0
#Contact: jland@redhat.com
#Generated by: https://openapi-generator.tech
#OpenAPI Generator version: 5.0.1
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for ::Todo
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ::Todo do

  describe "test an instance of Todo" do
    it "should create an instance of Todo" do
      #instance = ::Todo.new
      #expect(instance).to be_instance_of(::Todo)
    end
  end
  describe "test attribute 'name'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'description'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'date'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'completed'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
