# #defaultTitle
#
##defaultDescription
#
#The version of the OpenAPI document: 0.1
#
#Generated by: https://openapi-generator.tech
#OpenAPI Generator version: 5.0.1
#

require "uri"

module Test
  class DefaultApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Auto generated using Swagger Inspector
    # @return [nil]
    def orgs_place_os_repos_get()
      orgs_place_os_repos_get_with_http_info()
      nil
    end

    # Auto generated using Swagger Inspector
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def orgs_place_os_repos_get_with_http_info()
      if @api_client.config.debugging
        Log.debug {"Calling API: DefaultApi.orgs_place_os_repos_get ..."}
      end
      # resource path
      local_var_path = "/orgs/PlaceOS/repos"

      # query parameters
      query_params = Hash(Symbol, String).new

      # header parameters
      header_params = Hash(String, String).new

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = nil

      # auth_names
      auth_names = [] of String

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DefaultApi.orgs_place_os_repos_get",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DefaultApi#orgs_place_os_repos_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end

    # Auto generated using Swagger Inspector
    # @return [nil]
    def repos_place_os_drivers_commits_get()
      repos_place_os_drivers_commits_get_with_http_info()
      nil
    end

    # Auto generated using Swagger Inspector
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def repos_place_os_drivers_commits_get_with_http_info()
      if @api_client.config.debugging
        Log.debug {"Calling API: DefaultApi.repos_place_os_drivers_commits_get ..."}
      end
      # resource path
      local_var_path = "/repos/PlaceOS/drivers/commits"

      # query parameters
      query_params = Hash(Symbol, String).new

      # header parameters
      header_params = Hash(String, String).new

      # form parameters
      form_params = Hash(Symbol, String).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = nil

      # auth_names
      auth_names = [] of String

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DefaultApi.repos_place_os_drivers_commits_get",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DefaultApi#repos_place_os_drivers_commits_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return nil, status_code, headers
    end
  end
end
