# #defaultTitle
#
##defaultDescription
#
#The version of the OpenAPI document: 0.1
#
#Generated by: https://openapi-generator.tech
#OpenAPI Generator version: 5.0.1
#

# Dependencies
require "crest"
require "log"

module Test
  Log = Test::Log.for("") # => Log for  source

  VERSION = {{ `shards version #{__DIR__}`.chomp.stringify }}

  # Customize default settings for the SDK using block.
  #   .configure do |config|
  #     config.username = "xxx"
  #     config.password = "xxx"
  #   end
  # If no block given, return the default Configuration object.
  def configure
    if block_given?
      yield(Configuration.default)
    else
      Configuration.default
    end
  end
end

require ".//**"
