# #defaultTitle
#
##defaultDescription
#
#The version of the OpenAPI document: 0.1
#
#Generated by: https://openapi-generator.tech
#OpenAPI Generator version: 5.0.1
#

require "../spec_helper"
require "json"
require "time"

# Unit tests for ::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe "DefaultApi" do
  describe "test an instance of DefaultApi" do
    it "should create an instance of DefaultApi" do
      api_instance = ::DefaultApi.new
      # TODO expect(api_instance).to be_instance_of(::DefaultApi)
    end
  end

  # unit tests for orgs_place_os_repos_get
  # Auto generated using Swagger Inspector
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "orgs_place_os_repos_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  # unit tests for repos_place_os_drivers_commits_get
  # Auto generated using Swagger Inspector
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe "repos_place_os_drivers_commits_get test" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
